"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Article = { id: number; title: string; deck: string; category: string; status: string; review_at: string | null; summary_json: string[]; body_json: { type: string; text?: string; title?: string }[] };

export default function EditorClient({ articleId }: { articleId: number }) {
  const [article, setArticle] = useState<Article | null>(null), [message, setMessage] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { fetch(`/api/admin/forum/articles/${articleId}`, { cache: "no-store" }).then((response) => response.json()).then((data) => setArticle(data.article ?? null)); }, [articleId]);
  async function save() { if (!article) return; setSaving(true); const response = await fetch(`/api/admin/forum/articles/${article.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: article.title, deck: article.deck, summary: article.summary_json, body: article.body_json, reviewAt: article.review_at }) }); setMessage(response.ok ? "수정 내용을 저장했습니다. 다시 검토가 필요합니다." : "저장하지 못했습니다."); setSaving(false); }
  async function publish(scheduledAt?: string) { if (!article) return; setSaving(true); const response = await fetch(`/api/admin/forum/articles/${article.id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scheduledAt: scheduledAt || null }) }); setMessage(response.ok ? (scheduledAt ? "예약 게시했습니다." : "승인 후 게시했습니다.") : "게시하지 못했습니다."); setSaving(false); }
  if (!article) return <main className="editor-shell"><div className="forum-empty"><strong>초안을 불러오고 있습니다</strong></div></main>;
  return <main className="editor-shell"><header className="editor-top"><Link href="/admin/forum/">← 대시보드</Link><div><span>{article.status === "review" ? "검토 대기" : article.status}</span><small>{message || "데이터베이스에 연결됨"}</small></div><div><button onClick={save} disabled={saving}>저장</button><button onClick={() => { const value = window.prompt("예약 일시를 입력하세요. 예: 2026-08-20T09:00:00+09:00"); if (value) publish(value); }} disabled={saving}>예약 게시</button><button className="primary" onClick={() => publish()} disabled={saving}>승인 후 게시</button></div></header><div className="editor-layout"><aside className="editor-outline"><strong>문서 구성</strong><a className="active" href="#summary">핵심 요약</a><a href="#detail">상세 내용</a><hr /><strong>콘텐츠 설정</strong><label>카테고리<select value={article.category} disabled><option>{article.category}</option></select></label><label>재검토일<input type="date" value={article.review_at?.slice(0, 10) ?? ""} onChange={(event) => setArticle({ ...article, review_at: event.target.value })} /></label></aside><article className="editor-document"><div className="editor-label">콘텐츠 초안 · #{article.id}</div><input className="editor-title" value={article.title} onChange={(event) => setArticle({ ...article, title: event.target.value })} aria-label="제목" /><textarea className="editor-deck-input" value={article.deck} onChange={(event) => setArticle({ ...article, deck: event.target.value })} aria-label="요약 설명" /><section id="summary"><h2>3줄 핵심 요약</h2><ol>{article.summary_json.map((item, index) => <li key={index}><textarea value={item} onChange={(event) => { const summary = [...article.summary_json]; summary[index] = event.target.value; setArticle({ ...article, summary_json: summary }); }} /></li>)}</ol></section><section id="detail"><h2>상세 내용</h2>{article.body_json.map((section, index) => section.text !== undefined ? <textarea key={index} value={section.text} onChange={(event) => { const body = [...article.body_json]; body[index] = { ...section, text: event.target.value }; setArticle({ ...article, body_json: body }); }} /> : section.title ? <h3 key={index}>{section.title}</h3> : null)}</section></article><aside className="editor-assistant"><div><span>AI 편집 도우미</span><i>다음 단계</i></div><p>현재는 실제 저장·승인·예약 기능이 연결되었습니다. AI 재작성과 출처 재검증은 자동화 단계에서 연결됩니다.</p><button disabled>쉽게 다시 쓰기</button><button disabled>공식 출처 재검증</button><div className="editor-note">수정 후 저장하면 승인 상태가 해제되고 검토 대기로 돌아갑니다.</div></aside></div></main>;
}
